project:
  type: book
  output-dir: _book

book:
  title: "Yaşam Bilimlerinde Veri Analizi"
  author: "Emrah Kırdök, Ph.D."
  date: "2023/02/23"
  favicon: "images/ybva.png"
  reader-mode: true

  sidebar:
    logo: "images/ybva.png"

  page-footer:
    left: |
      Yaşam Bilimlerinde Veri Analizi
      Emrah Kırdök, Ph.D.
    right: |
      Bu kitap Veri Analizi, İstatistiksel Öğrenme, ve
      Yaşam Bilimlerinde Veri Analizi Dersleri için
      kaynak olarak kullanılacaktır.
  site-url: https://emrahkirdok.github.io/ybva/
  repo-url: https://github.com/emrahkirdok/ybva/
  
  chapters:
    - index.qmd
    - CONTRIBUTING.md
    
    - part: "Derse Hazırlık"
      chapters:
        - 01-kurulum/01-r-rstudio-kurulum.qmd
        - 01-kurulum/02-ilk-kurallar.qmd
        - 01-kurulum/03-r-rstudio-ilk-adimlar.qmd
        - 01-kurulum/04-klasor-islemleri.qmd

    - part: "Veri Analizi"
      chapters:
        - 02-veri-analizi/01-veri-bilimine-giris.qmd
        - 02-veri-analizi/02-bilimsel-yontem.qmd
        - 02-veri-analizi/03-r-giris.qmd
        - 02-veri-analizi/04-vektorler.qmd
        - 02-veri-analizi/05-matrisler.qmd
        - 02-veri-analizi/06-veri-cerceveleri.qmd
        - 02-veri-analizi/14-veri-cercevesi-bulmacalari-01.Rmd
        - 02-veri-analizi/07-listeler.qmd
        - 02-veri-analizi/08-dosya-okuma.qmd
        - 02-veri-analizi/09-rmarkdown.Rmd
        - 02-veri-analizi/10-bilimsel-hikaye-01.qmd
        - 02-veri-analizi/11-bilimsel-hikaye-02.qmd
        - 02-veri-analizi/12-bilimsel-hikaye-03.qmd
        - 02-veri-analizi/13-t-test.qmd
        - 02-veri-analizi/dogrusal-modelleme-1.qmd
        - 02-veri-analizi/dogrusal-modelleme-2.qmd
        
    - part: "Bilgisayarlı Düşünme"
      chapters:
        - 03-bilgisayarli-dusunme/01-ileri-seviye-r-01.qmd
        - 03-bilgisayarli-dusunme/02-ileri-seviye-r-02.qmd
        - 03-bilgisayarli-dusunme/03-dna-dizisi-yukleme.qmd
        - 03-bilgisayarli-dusunme/04-dna-dizi-islemleri.qmd
        - 03-bilgisayarli-dusunme/05-dna-dizi-islemleri.qmd
        - 03-bilgisayarli-dusunme/06-adim-adim-kodlama-translasyon.qmd
        - 03-bilgisayarli-dusunme/07-rnaseq-data-analysis.qmd
#        - metin_asamali_azalis.Rmd
#        - metin_amphiBIO_calisma.Rmd
    
    - part: "Pratikler - Ödevler"
      chapters:
        - 04-pratikler/01-veri-analizi/01-vektorler.qmd
        - 04-pratikler/01-veri-analizi/02-pratik.Rmd
        - 04-pratikler/01-veri-analizi/04-vize-pratik.qmd
        - 04-pratikler/01-veri-analizi/05-vize-pratik-2024-05-30.Rmd
        - 04-pratikler/01-veri-analizi/matris-veri-cercevesi-pratik.Rmd
        - 04-pratikler/01-veri-analizi/liste-pratik.Rmd
        - 04-pratikler/02-bilgisayarli-dusunme/01-DNA-transkripsiyon.qmd
        - 04-pratikler/02-bilgisayarli-dusunme/03-vize-sinavi-cevaplari.qmd
        
    - part: "Biyoteknolojide Veri Analizi"
      chapters:
        - 05-istatistik/naive-bayes.qmd
        - 05-istatistik/lojistik-regresyon.qmd
        - 05-istatistik/random-forest.qmd
        - 05-istatistik/odev.qmd
    - part: "Türkiye'nin Verisi"
  
    - references.qmd

  appendices:
    - 10-ekler/01-sunumlar.qmd


bibliography : bibliography.bib
lang: tr

language:
  tr:
    crossref-fig-title: "Şekil"

format:
  html:
    mainfont: helvetica
    theme:
      - darkly
    code-link: true
  pdf:
    documentclass: scrbook
    author-meta: "Emrah Kırdök"
