on:
  workflow_dispatch:
  push:
    branches: main

name: Publish quarto website
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R packages
        uses: r-lib/actions/setup-r-dependencies@v2
           
      #- name: Render Quarto Project
      #  uses: quarto-dev/quarto-actions/render@v2
      #  with:
      #    path: source-folder
      #    to: html
     
      - name: Render book to html
        # Add any command line argument needed
        run: |
          quarto render --to html

      - name: Render presentations
        run: |
          quarto render 00-sunumlar/01-veri-analizi/01-00-preface.qmd;
          quarto render 00-sunumlar/01-veri-analizi/01-01-r-giris.qmd
          quarto render 00-sunumlar/01-veri-analizi/01-02-vektorler.qmd
          quarto render 00-sunumlar/01-veri-analizi/01-03-matrisler.qmd
          quarto render 00-sunumlar/01-veri-analizi/01-04-veri-cerceveleri.qmd
          quarto render 00-sunumlar/02-bilgisayarli-dusunme/02-01-ileri-seviye-r-01.qmd
          quarto render 00-sunumlar/02-bilgisayarli-dusunme/02-02-ileri-seviye-r-02.qmd
      
      - name: Copy presentations to book
        run: |
          mkdir -p _book/00-sunumlar; cp 00-sunumlar/*/*.html _book/00-sunumlar

      - name: Publish book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
